$mainMod = SUPER
$files = pcmanfm
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$rofiDir = $HOME/.config/rofi

# wofi manager
# bind = SUPER, D, exec, wofi --show drun

bind = SUPER, D, exec, $rofiDir/launchers/type-3/launcher.sh

#wofi emoji
bind = SUPER, e, exec, wofimoji

bind = $mainMod, Return, exec, $term  # Launch terminal
bind = $mainMod, T, exec, pcmanfm # Launch File Manager

