[FileDialog]
history=file:///home/man37/Downloads/Telegram Desktop/FamilyMan_S01, file:///home/man37/Downloads/Panchayat (2025) S04 COMPLETE Hindi (720p 10bit AMZN WEBRip x265 ESub) [PMZ], file:///home/man37, file:///home/man37/Downloads, file:///home/man37/Downloads/Telegram Desktop
lastVisited=file:///home/man37/Downloads/Telegram Desktop
qtVersion=5.15.17
shortcuts=file:, file:///home/man37
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
